baseurl = "https://halleygen.github.io/auxiliar-project/"
title = "Jesse's Portfolio"
theme = ["hugo-learn"]
languageCode = "en-au"


[params]
  themeVariant = "blue"
  author = "Jesse"
  description = "Jesse's 2018/2019 Madrid Language Assistant Portfolio"
  disableNextPrev = true

#[[menu.main]]
#	name = "Home"
#	weight = 0
#	url = "/"
#[[menu.main]]
#	name = "About"
#	weight = 0
#	url = "/about"
#[[menu.main]]
#	name = "Portfolio"
#	weight = 0
#	url = "/portfolio"
#[[menu.main]]
#	name = "Australia Day"
#	weight = 0
#	url = "/australia-day"
	
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]