baseurl = "https://halleygen.github.io/auxiliar-project/"
title = "Jesse's Portfolio"
theme = ["hugo-learn"]
languageCode = "en-au"

[params]
  themeVariant = "blue"
  author = "Jesse"
  description = "Jesse's 2018/2019 Madrid Language Assistant Portfolio"
	
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]