baseurl = "https://halleygen.github.io/auxiliar-project/"
title = "Jesse's Portfolio"
theme = "creative-portfolio"
languageCode = "en-au"

[params]
  style = "red"
  author = "Jesse"
  description = "Jesse's 2018/2019 Madrid Language Assistant Portfolio"
  sidebarAbout = [
    "Hello! My name is Jesse. I'm an Australian who is taking part in the 2018/2019 Auxiliares de Conversación programme.",
    "I work at CEIP El Peralejo, which is located in Alpedrete, Madrid. My students range from 3 yrs olds to 6th graders."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "home/"
  home = true

  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"

  [[params.navlinks]]
  name = "Final Project"
  url = "final-project/" 