baseurl = "https://halleygen.github.io/auxiliar-project/"
title = "Jesse's Portfolio"
theme = "hugo-learn"
languageCode = "en-au"


[params]
  themeVariant = "blue"
  author = "Jesse"
  description = "Jesse's 2018/2019 Madrid Language Assistant Portfolio"
  disableNextPrev = true

  sidebarAbout = [
    "Hello! My name is Jesse. I'm an Australian who is taking part in the 2018/2019 Auxiliares de Conversación programme.",
    "I work at CEIP El Peralejo, which is located in Alpedrete, Madrid. My students range from 3 yrs olds to 6th graders."
  ] 

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]