baseurl = "https://halleygen.github.io/auxiliar-project/"
title = "Jesse's Portfolio"
theme = "creative-portfolio"
languageCode = "en-au"

disqusShortname = ""
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "red"
  description = "2018/2019 Madrid Language Assistant Portfolio"
  #copyright = "&copy;2016 Your name or company"
  sidebarAbout = [
    "Hello! My name is Jesse. I'm an Australian who is taking part in the 2018/2019 Auxiliares de Conversación programme.",
    "I work at CEIP El Peralejo and help to teach English to kids from 3yrs old to 6th grade."
  ]

  email = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "home/"
  home = true

  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"

  [[params.navlinks]]
  name = "Final Project"
  url = "final-project/" 