baseurl = "https://halleygen.github.io/auxiliar-project/"
title = "Jesse's Portfolio"
theme = "creative-portfolio"
languageCode = "en-au"

disqusShortname = ""
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "red"
  description = "Describe your website"
  #copyright = "&copy;2016 Your name or company"
  sidebarAbout = [
    "I am a creative illustrator and graphic designer with more than 10 years of experience.",
    "Originally from Toronto, currently based in London."
  ]

  email = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/" 